# config.yaml
paths:
  input_file: './data/inputv2.csv'
  output_file: './data/output_datav2.csv'
  log_file: './logs/extract_data.log'

logging:
  level: 'ERROR'
  format: '%(asctime)s:%(levelname)s:%(message)s'